// @vitest-environment node
// Cross-runtime equivalence: this TS implementation must reproduce the SAME
// vectors.json the native Rust engine pins against (generated by the
// independent python3 reference libs/games/scripts/gen_vectors.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { vectorsUrl } from './vectors-path';
import { describe, expect, it } from 'vitest';
import { payoutUnits } from './ints';
import { bytesToHex, deriveSeed, hexToBytes, rawU64 } from './seed';
import {
    FRACTIONAL_POW2_PPM,
    GAME_TYPE,
    MAX_MULTIPLIER_CAP_PPM,
    MAX_ROUND_TICK_CAP,
    crashPointPpm,
    crashRound,
    crashTick,
    decodeCashoutTick,
    decodeConfig,
    multiplierPpm,
    replay,
} from './crash';
import { ReplayError, type TranscriptAction } from './types';
import { supportedGameTypes } from '../verifier';

interface MultiplierVector {
    n: number;
    m_ppm: number;
}

interface RoundVector {
    server_seed: string;
    client_seed: string;
    raw_u64: string;
    crash_point_ppm: number;
    crash_tick: number;
    max_win_multiplier_ppm: number;
}

/**
 * A whole settled round, as the SHIPPED RUST engine and adapter produce it.
 *
 * `payload_hex` is the verbatim output of `GameAdapter::encode_action_borsh`,
 * which is exactly what rides in the transcript's `TranscriptAction::payload`
 * — so these rows pin this port to the Rust Borsh layout and not merely to the
 * Rust arithmetic. A field-order or width change on the Rust side turns them
 * red here. Amounts are decimal strings of `u128` atomic units (TEZ, 6 dp).
 */
interface TranscriptVector {
    name: string;
    server_seed: string;
    client_seed: string;
    stake_units: string;
    actions: { index: number; action_type: string; payload_hex: string }[];
    expected_outcome: string;
    expected_cumulative_ppm: number;
    expected_payout_units: string;
}

const vectors: {
    fractional_pow2_ppm: number[];
    multiplier_vectors: MultiplierVector[];
    round_vectors: RoundVector[];
    transcript_vectors: TranscriptVector[];
} = JSON.parse(readFileSync(fileURLToPath(vectorsUrl('crash')), 'utf8'));

/** A `place-bet` payload: `borsh(Config { auto_cashout_tick: Option<u32> })`. */
function placeBetPayload(autoCashoutTick: number | null): Uint8Array {
    if (autoCashoutTick === null) {
        return new Uint8Array([0x00]);
    }

    return new Uint8Array([0x01, ...u32Le(autoCashoutTick)]);
}

/** A `cashout` payload: `borsh(u32 tick)`. */
function u32Le(value: number): Uint8Array {
    const bytes = new Uint8Array(4);

    new DataView(bytes.buffer).setUint32(0, value, true);

    return bytes;
}

function round(autoCashoutTick: number | null, tail: TranscriptAction[]): TranscriptAction[] {
    return [{ actionIndex: 0, actionType: 'place-bet', payload: placeBetPayload(autoCashoutTick) }, ...tail];
}

function cashout(tick: number): TranscriptAction {
    return { actionIndex: 1, actionType: 'cashout', payload: u32Le(tick) };
}

// server-2 / client-seed: crash_tick 41, so tick 40 is the last winning tick.
const CRASH_AT_41 = vectors.round_vectors.find((rv) => rv.crash_tick === 41);
const STAKE_MUTEZ = 100_000_000n; // 100 TEZ

describe('crash:v1 vectors', () => {
    it('carries the canonical fractional table, byte for byte', () => {
        expect(FRACTIONAL_POW2_PPM).toHaveLength(100);
        expect(FRACTIONAL_POW2_PPM.map(Number)).toEqual(vectors.fractional_pow2_ppm);
        // m(0) = 1.00×, and the table IS the curve between doublings.
        expect(FRACTIONAL_POW2_PPM[0]).toBe(1_000_000n);
    });

    it('reproduces every multiplier vector, including the cap clamp', () => {
        expect(vectors.multiplier_vectors.length).toBeGreaterThan(0);

        for (const mv of vectors.multiplier_vectors) {
            expect(multiplierPpm(BigInt(mv.n))).toBe(BigInt(mv.m_ppm));
        }

        // The cap rows above are only meaningful if the cap is where it claims:
        // m(996) is the greatest multiplier within the 1000× exposure cap.
        expect(multiplierPpm(MAX_ROUND_TICK_CAP) <= MAX_MULTIPLIER_CAP_PPM).toBe(true);
        expect(crashTick(MAX_MULTIPLIER_CAP_PPM)).toBe(MAX_ROUND_TICK_CAP);
    });

    it('reproduces every round vector: raw u64, crash point, crash tick, best cashout', () => {
        expect(vectors.round_vectors).toHaveLength(6);

        for (const rv of vectors.round_vectors) {
            const seed = deriveSeed(GAME_TYPE, rv.server_seed, rv.client_seed, 0);

            expect(rawU64(seed).toString()).toBe(rv.raw_u64);

            const derived = crashRound(rv.server_seed, rv.client_seed);

            expect(derived.seedHex).toBe(bytesToHex(seed));
            expect(derived.rawU64.toString()).toBe(rv.raw_u64);
            expect(crashPointPpm(BigInt(rv.raw_u64))).toBe(BigInt(rv.crash_point_ppm));
            expect(derived.crashPointPpm).toBe(BigInt(rv.crash_point_ppm));
            expect(crashTick(BigInt(rv.crash_point_ppm))).toBe(BigInt(rv.crash_tick));
            expect(derived.crashTick).toBe(BigInt(rv.crash_tick));
            expect(derived.maxWinMultiplierPpm).toBe(BigInt(rv.max_win_multiplier_ppm));
        }
    });

    it('covers both clamp endpoints with real vector rows', () => {
        const instantBust = vectors.round_vectors.find((rv) => rv.crash_tick === 0);
        const atCap = vectors.round_vectors.find((rv) => rv.crash_tick === 996);

        // The instant-bust row: crash point floored to 1.00×, no winning tick.
        expect(instantBust).toBeDefined();
        expect(instantBust?.crash_point_ppm).toBe(1_000_000);
        expect(instantBust?.max_win_multiplier_ppm).toBe(0);

        // The cap row: crash point ceilinged to 1000×, curve stops at tick 996.
        expect(atCap).toBeDefined();
        expect(atCap?.crash_point_ppm).toBe(1_000_000_000);

        // Every cashout on an instant-bust round loses, tick 0 included.
        const bust = instantBust as RoundVector;
        const busted = replay(bust.server_seed, bust.client_seed, round(null, [cashout(0)]));

        expect(busted.outcome).toBe('lose');
        expect(busted.cumulativePpm).toBe(0n);
        expect(payoutUnits(STAKE_MUTEZ, busted.cumulativePpm)).toBe(0n);
    });
});

describe('crash:v1 replay', () => {
    it('pays a manual cashout below the crash at m(tick)', () => {
        const rv = CRASH_AT_41 as RoundVector;
        const result = replay(rv.server_seed, rv.client_seed, round(null, [cashout(40)]));

        expect(result.settled).toBe(true);
        expect(result.outcome).toBe('cashout');
        expect(result.cumulativePpm).toBe(multiplierPpm(40n));
        expect(result.cumulativePpm).toBe(BigInt(rv.max_win_multiplier_ppm)); // tick 40 is the best available
        expect(payoutUnits(STAKE_MUTEZ, result.cumulativePpm)).toBe(131_950_800n);
        expect(result.steps.map((s) => s.actionType)).toEqual(['place-bet', 'cashout']);
        // place-bet leaves the round in progress at 1.00× in both modes.
        expect(result.steps[0].cumulativePpm).toBe(1_000_000n);
    });

    it('settles an auto round at its pre-committed target tick', () => {
        const rv = CRASH_AT_41 as RoundVector;
        const actions = round(20, [cashout(20)]);

        expect(decodeConfig(actions[0].payload).autoCashoutTick).toBe(20n);

        const result = replay(rv.server_seed, rv.client_seed, actions);

        expect(result.outcome).toBe('cashout');
        expect(result.cumulativePpm).toBe(multiplierPpm(20n));
        expect(payoutUnits(STAKE_MUTEZ, result.cumulativePpm)).toBe(114_869_800n); // m(20) = 1.148698×
    });

    it('loses a cashout at or past the crash tick', () => {
        const rv = CRASH_AT_41 as RoundVector;

        for (const tick of [41, 42, 996]) {
            const result = replay(rv.server_seed, rv.client_seed, round(null, [cashout(tick)]));

            expect(result.outcome).toBe('lose');
            expect(result.cumulativePpm).toBe(0n);
        }
    });

    it('loses a u32::MAX cashout — the comparison is on the UNCLAMPED tick', () => {
        const rv = CRASH_AT_41 as RoundVector;
        const actions = round(null, [cashout(0xffff_ffff)]);

        expect(decodeCashoutTick(actions[1].payload)).toBe(4_294_967_295n);

        const result = replay(rv.server_seed, rv.client_seed, actions);

        expect(result.outcome).toBe('lose');
        expect(result.cumulativePpm).toBe(0n);
        expect(payoutUnits(STAKE_MUTEZ, result.cumulativePpm)).toBe(0n);
        // Had the tick been clamped to the cap before the comparison the way
        // multiplierPpm clamps it, this would have paid m(996) = 995.99872×.
        expect(multiplierPpm(4_294_967_295n)).toBe(multiplierPpm(MAX_ROUND_TICK_CAP));
    });

    it('settles expire and abandon as lose / 0', () => {
        const rv = CRASH_AT_41 as RoundVector;

        for (const actionType of ['expire', 'abandon']) {
            const result = replay(
                rv.server_seed,
                rv.client_seed,
                round(null, [{ actionIndex: 1, actionType, payload: new Uint8Array() }]),
            );

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe('lose');
            expect(result.cumulativePpm).toBe(0n);
        }
    });

    it('NEGATIVE: one mutated payload byte changes the payout, so the replay check fails', () => {
        const rv = CRASH_AT_41 as RoundVector;
        const honest = round(null, [cashout(40)]);
        const honestResult = replay(rv.server_seed, rv.client_seed, honest);
        const claimedPayout = payoutUnits(STAKE_MUTEZ, honestResult.cumulativePpm);

        // Flip the low byte of the borsh u32 tick: 40 → 39, one tick earlier.
        const tampered = round(null, [cashout(40)]);

        tampered[1].payload[0] = 39;

        const tamperedResult = replay(rv.server_seed, rv.client_seed, tampered);

        expect(tamperedResult.cumulativePpm).not.toBe(honestResult.cumulativePpm);
        expect(tamperedResult.cumulativePpm).toBe(multiplierPpm(39n));

        // This is the comparison verifier.ts's `replay-payout` check makes: the
        // recomputed payout no longer equals the payout the transcript claimed.
        expect(payoutUnits(STAKE_MUTEZ, tamperedResult.cumulativePpm)).not.toBe(claimedPayout);
    });

    it('rejects a malformed transcript', () => {
        const rv = CRASH_AT_41 as RoundVector;
        const rejects = (actions: TranscriptAction[]) =>
            expect(() => replay(rv.server_seed, rv.client_seed, actions)).toThrow(ReplayError);

        rejects([]);
        rejects([cashout(1)]); // no place-bet at index 0
        rejects(round(null, [cashout(1), cashout(2)])); // a second in-round action
        rejects(round(null, [{ actionIndex: 1, actionType: 'reveal', payload: new Uint8Array() }]));
        rejects(round(null, [{ actionIndex: 1, actionType: 'cashout', payload: new Uint8Array([1, 2, 3]) }]));
        rejects([{ actionIndex: 0, actionType: 'place-bet', payload: new Uint8Array([0x02]) }]);
        rejects([{ actionIndex: 0, actionType: 'place-bet', payload: new Uint8Array([0x00, 0x00]) }]);
    });

    it('is registered with the verifier', () => {
        expect(supportedGameTypes()).toHaveLength(4);
        expect(supportedGameTypes()).toContain(GAME_TYPE);
    });
});

// ── whole rounds, against the Rust engine's own bytes ───────────────────

describe('crash:v1 transcript vectors', () => {
    // Everything above pins the CURVE: seeds, multipliers, crash ticks. These
    // rows pin the ROUND — the exact Borsh payload bytes the shipped Rust
    // adapter writes for each action, and the outcome and payout the shipped
    // Rust engine produces from them. Nothing here is hand-derived: the
    // payloads are decoded from the file rather than rebuilt by this test's own
    // encoder, which is the point. A Rust-side layout change (a field reordered,
    // a width narrowed, `Option` tagging altered) cannot pass this file by.

    const TRANSCRIPT_VECTORS = vectors.transcript_vectors;

    function actionsOf(vector: TranscriptVector): TranscriptAction[] {
        return vector.actions.map((action) => ({
            actionIndex: action.index,
            actionType: action.action_type,
            payload: hexToBytes(action.payload_hex),
        }));
    }

    it('has vectors covering every action type, or the walk below is vacuous', () => {
        expect(TRANSCRIPT_VECTORS.length).toBeGreaterThanOrEqual(7);

        const types = new Set(TRANSCRIPT_VECTORS.flatMap((v) => v.actions.map((a) => a.action_type)));

        // All three, because each exercises a different arm of the replayer:
        // the config decode, the claimed-tick comparison, and the system
        // settle that takes no payload at all.
        expect(types).toEqual(new Set(['place-bet', 'cashout', 'expire']));
        // Both outcomes, or a replayer that returned one constant would pass.
        expect(TRANSCRIPT_VECTORS.some((v) => v.expected_outcome === 'cashout')).toBe(true);
        expect(TRANSCRIPT_VECTORS.some((v) => v.expected_outcome === 'lose')).toBe(true);
    });

    it.each(TRANSCRIPT_VECTORS.map((vector) => [vector.name, vector] as const))(
        'replays %s to the Rust engine’s own outcome and payout',
        (_name, vector) => {
            const result = replay(vector.server_seed, vector.client_seed, actionsOf(vector));

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe(vector.expected_outcome);
            expect(result.cumulativePpm).toBe(BigInt(vector.expected_cumulative_ppm));
            // The payout rule at the trust boundary, at the asset's 6 dp — the
            // same helper `verifier.ts`'s `replay-payout` check compares with.
            expect(payoutUnits(BigInt(vector.stake_units), result.cumulativePpm)).toBe(
                BigInt(vector.expected_payout_units),
            );
            expect(result.steps.map((step) => step.actionType)).toEqual(
                vector.actions.map((action) => action.action_type),
            );
        },
    );

    it('decodes each vector’s config and claimed tick from the file’s own bytes', () => {
        // The payload bytes are load-bearing and not decoration: read them back
        // through the decoders the replay itself uses, so a row whose hex the
        // replayer happened to ignore cannot sit here looking checked.
        for (const vector of TRANSCRIPT_VECTORS) {
            const actions = actionsOf(vector);
            const config = decodeConfig(actions[0].payload);
            const settle = actions[1];

            if (config.autoCashoutTick === null) {
                expect(actions[0].payload).toEqual(new Uint8Array([0x00]));
            } else {
                expect(actions[0].payload[0]).toBe(0x01);
                expect(actions[0].payload).toHaveLength(5);
            }

            if (settle.actionType === 'cashout') {
                const claimed = decodeCashoutTick(settle.payload);

                expect(settle.payload).toHaveLength(4);
                // An AUTO round's settling cashout is the sweep writing the
                // pre-committed target back, so the two numbers must agree.
                if (config.autoCashoutTick !== null) {
                    expect(claimed).toBe(config.autoCashoutTick);
                }
            } else {
                expect(settle.actionType).toBe('expire');
                expect(settle.payload).toHaveLength(0);
            }
        }
    });
});
