// @vitest-environment node
// Cross-runtime equivalence: this TS implementation must reproduce the SAME
// vectors.json the native Rust engine pins against (generated by the
// independent python3 reference libs/games/scripts/gen_vectors.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { vectorsUrl } from './vectors-path';
import { describe, expect, it } from 'vitest';
import { bytesToHex, deriveSeed, hexToBytes, rawU64 } from './seed';
import {
    FRACTIONAL_POW2_PPM,
    GAME_TYPE,
    MAX_MULTIPLIER_CAP_PPM,
    MAX_ROUND_TICK_CAP,
    crashPointPpm,
    crashRound,
    crashTick,
    decodeCashoutTick,
    decodeConfig,
    multiplierPpm,
    replay,
} from './crash';
import { payoutUnits } from './ints';
import { ReplayError, type TranscriptAction } from './types';
import { supportedGameTypes } from '../verifier';

/** The seed rule every listed deployment selects today. */

interface MultiplierVector {
    n: number;
    m_ppm: number;
}

interface RoundVector {
    /** Present on the rows a test addresses by name; the predicate is what the generator searched for. */
    name?: string;
    predicate?: string;
    /** The generator's search counter for a named row. */
    search_index?: number;
    server_seed: string;
    client_seed: string;
    raw_u64: string;
    crash_point_ppm: number;
    crash_tick: number;
    max_win_multiplier_ppm: number;
}

/**
 * A whole settled round, as the SHIPPED RUST engine and adapter produce it.
 *
 * `payload_hex` is the verbatim output of `GameAdapter::encode_action_borsh`,
 * which is exactly what rides in the transcript's `TranscriptAction::payload`
 * — so these rows pin this port to the Rust Borsh layout and not merely to the
 * Rust arithmetic. A field-order or width change on the Rust side turns them
 * red here. Amounts are decimal strings of `u128` atomic units (TEZ, 6 dp).
 */
interface TranscriptVector {
    name: string;
    server_seed: string;
    client_seed: string;
    stake_units: string;
    actions: { index: number; action_type: string; payload_hex: string }[];
    expected_outcome: string;
    expected_cumulative_ppm: number;
    expected_payout_units: string;
}

const vectors: {
    fractional_pow2_ppm: number[];
    multiplier_vectors: MultiplierVector[];
    round_vectors: RoundVector[];
    transcript_vectors: TranscriptVector[];
} = JSON.parse(readFileSync(fileURLToPath(vectorsUrl('crash')), 'utf8'));

/** A `place-bet` payload: `borsh(Config { auto_cashout_tick: Option<u32> })`. */
function placeBetPayload(autoCashoutTick: number | null): Uint8Array {
    if (autoCashoutTick === null) {
        return new Uint8Array([0x00]);
    }

    return new Uint8Array([0x01, ...u32Le(autoCashoutTick)]);
}

/** A `cashout` payload: `borsh(u32 tick)`. */
function u32Le(value: number): Uint8Array {
    const bytes = new Uint8Array(4);

    new DataView(bytes.buffer).setUint32(0, value, true);

    return bytes;
}

function round(autoCashoutTick: number | null, tail: TranscriptAction[]): TranscriptAction[] {
    return [{ actionIndex: 0, actionType: 'place-bet', payload: placeBetPayload(autoCashoutTick) }, ...tail];
}

function cashout(tick: number): TranscriptAction {
    return { actionIndex: 1, actionType: 'cashout', payload: u32Le(tick) };
}

/**
 * A round vector addressed by its NAME, never by a seed-derived value. The
 * generator searches for each named row's seed until its predicate holds; when
 * the seed derivation changes it appends a freshly searched row rather than
 * editing an existing one, so the tests below follow the name and never a
 * hardcoded tick or a row position.
 */
function namedRound(name: string): RoundVector {
    const row = vectors.round_vectors.find((rv) => rv.name === name);

    if (row === undefined) {
        throw new Error(`crash vectors.json has no round_vectors row named ${name}`);
    }

    return row;
}

// Predicate 41 <= crash_tick <= 100: a mid-curve round with room for a winning
// auto target well below the crash and a losing claim past it.
const MID_CURVE = namedRound('crash-mid-curve');
const CRASH_TICK = BigInt(MID_CURVE.crash_tick);
/** The last winning tick: a cashout here takes the round's best multiplier. */
const LAST_WIN_TICK = CRASH_TICK - 1n;
/** An auto target comfortably inside the winning range. */
const AUTO_TICK = CRASH_TICK / 2n;
const STAKE_MUTEZ = 100_000_000n; // 100 TEZ

describe('crash:v1 vectors', () => {
    it('carries the canonical fractional table, byte for byte', () => {
        expect(FRACTIONAL_POW2_PPM).toHaveLength(100);
        expect(FRACTIONAL_POW2_PPM.map(Number)).toEqual(vectors.fractional_pow2_ppm);
        // m(0) = 1.00×, and the table IS the curve between doublings.
        expect(FRACTIONAL_POW2_PPM[0]).toBe(1_000_000n);
    });

    it('reproduces every multiplier vector, including the cap clamp', () => {
        expect(vectors.multiplier_vectors.length).toBeGreaterThan(0);

        for (const mv of vectors.multiplier_vectors) {
            expect(multiplierPpm(BigInt(mv.n))).toBe(BigInt(mv.m_ppm));
        }

        // The cap rows above are only meaningful if the cap is where it claims:
        // m(996) is the greatest multiplier within the 1000× exposure cap.
        expect(multiplierPpm(MAX_ROUND_TICK_CAP) <= MAX_MULTIPLIER_CAP_PPM).toBe(true);
        expect(crashTick(MAX_MULTIPLIER_CAP_PPM)).toBe(MAX_ROUND_TICK_CAP);
    });

    it('reproduces every round vector: raw u64, crash point, crash tick, best cashout', () => {
        // No hardcoded total and no unnamed count: a searched seed that equals
        // an existing row's names that row in place, otherwise it is APPENDED,
        // so neither number is stable. Six original rows is the floor, and
        // every name the tests address must be present as a searched row.
        expect(vectors.round_vectors.length).toBeGreaterThanOrEqual(6);

        for (const name of ['crash-mid-curve', 'crash-instant-bust', 'crash-at-cap']) {
            expect(namedRound(name).search_index).toBeTypeOf('number');
        }

        for (const rv of vectors.round_vectors) {
            const seed = deriveSeed(GAME_TYPE, rv.server_seed, rv.client_seed, 0, 0);

            expect(rawU64(seed).toString()).toBe(rv.raw_u64);

            const derived = crashRound(rv.server_seed, rv.client_seed);

            expect(derived.seedHex).toBe(bytesToHex(seed));
            expect(derived.rawU64.toString()).toBe(rv.raw_u64);
            expect(crashPointPpm(BigInt(rv.raw_u64))).toBe(BigInt(rv.crash_point_ppm));
            expect(derived.crashPointPpm).toBe(BigInt(rv.crash_point_ppm));
            expect(crashTick(BigInt(rv.crash_point_ppm))).toBe(BigInt(rv.crash_tick));
            expect(derived.crashTick).toBe(BigInt(rv.crash_tick));
            expect(derived.maxWinMultiplierPpm).toBe(BigInt(rv.max_win_multiplier_ppm));
        }
    });

    it('covers both clamp endpoints with real vector rows', () => {
        const instantBust = namedRound('crash-instant-bust');
        const atCap = namedRound('crash-at-cap');

        // The instant-bust row: crash point floored to 1.00×, no winning tick.
        expect(instantBust.crash_tick).toBe(0);
        expect(instantBust.crash_point_ppm).toBe(1_000_000);
        expect(instantBust.max_win_multiplier_ppm).toBe(0);

        // The cap row: crash point ceilinged to 1000×, curve stops at tick 996.
        expect(atCap.crash_tick).toBe(Number(MAX_ROUND_TICK_CAP));
        expect(atCap.crash_point_ppm).toBe(1_000_000_000);

        // Every cashout on an instant-bust round loses, tick 0 included.
        const busted = replay(instantBust.server_seed, instantBust.client_seed, round(null, [cashout(0)]), STAKE_MUTEZ);

        expect(busted.outcome).toBe('lose');
        expect(busted.cumulativePpm).toBe(0n);
        expect(busted.payoutUnits).toBe(0n);
    });
});

describe('crash:v1 replay', () => {
    it('runs on a mid-curve row that still satisfies its predicate', () => {
        // Every derived tick below leans on this range: a winning auto target
        // strictly inside (0, crash), and a tick that fits one borsh byte.
        expect(CRASH_TICK).toBeGreaterThanOrEqual(41n);
        expect(CRASH_TICK).toBeLessThanOrEqual(100n);
    });

    it('pays a manual cashout below the crash at m(tick)', () => {
        const rv = MID_CURVE;
        const result = replay(rv.server_seed, rv.client_seed, round(null, [cashout(Number(LAST_WIN_TICK))]), STAKE_MUTEZ);

        expect(result.settled).toBe(true);
        expect(result.outcome).toBe('cashout');
        expect(result.cumulativePpm).toBe(multiplierPpm(LAST_WIN_TICK));
        expect(result.cumulativePpm).toBe(BigInt(rv.max_win_multiplier_ppm)); // the last winning tick is the best available
        // Consistency only: payoutUnits is the helper replay itself calls. The
        // payout math is pinned independently by the transcript_vectors below.
        expect(result.payoutUnits).toBe(payoutUnits(STAKE_MUTEZ, multiplierPpm(LAST_WIN_TICK)));
        // A strict win, so the payout figure discriminates a cashout from a refund.
        expect(result.payoutUnits).toBeGreaterThan(STAKE_MUTEZ);
        expect(result.steps.map((s) => s.actionType)).toEqual(['place-bet', 'cashout']);
        // place-bet leaves the round in progress at 1.00× in both modes.
        expect(result.steps[0].cumulativePpm).toBe(1_000_000n);
    });

    it('settles an auto round at its pre-committed target tick', () => {
        const rv = MID_CURVE;
        const actions = round(Number(AUTO_TICK), [cashout(Number(AUTO_TICK))]);

        expect(decodeConfig(actions[0].payload).autoCashoutTick).toBe(AUTO_TICK);

        const result = replay(rv.server_seed, rv.client_seed, actions, STAKE_MUTEZ);

        expect(result.outcome).toBe('cashout');
        expect(result.cumulativePpm).toBe(multiplierPpm(AUTO_TICK));
        // Consistency only; payout math is pinned by the transcript_vectors below.
        expect(result.payoutUnits).toBe(payoutUnits(STAKE_MUTEZ, multiplierPpm(AUTO_TICK)));
    });

    it('loses a cashout at or past the crash tick', () => {
        const rv = MID_CURVE;

        for (const tick of [CRASH_TICK, CRASH_TICK + 1n, MAX_ROUND_TICK_CAP].map(Number)) {
            const result = replay(rv.server_seed, rv.client_seed, round(null, [cashout(tick)]), STAKE_MUTEZ);

            expect(result.outcome).toBe('lose');
            expect(result.cumulativePpm).toBe(0n);
        }
    });

    it('loses a u32::MAX cashout — the comparison is on the UNCLAMPED tick', () => {
        const rv = MID_CURVE;
        const actions = round(null, [cashout(0xffff_ffff)]);

        expect(decodeCashoutTick(actions[1].payload)).toBe(4_294_967_295n);

        const result = replay(rv.server_seed, rv.client_seed, actions, STAKE_MUTEZ);

        expect(result.outcome).toBe('lose');
        expect(result.cumulativePpm).toBe(0n);
        expect(result.payoutUnits).toBe(0n);
        // Had the tick been clamped to the cap before the comparison the way
        // multiplierPpm clamps it, this would have paid m(996) = 995.99872×.
        expect(multiplierPpm(4_294_967_295n)).toBe(multiplierPpm(MAX_ROUND_TICK_CAP));
    });

    it('settles expire, and a manual-round abandon, as lose / 0', () => {
        // A manual round has no cashout for the kernel to substitute on an
        // abandon, so it forfeits — the same loss as the sweep's expire.
        const rv = MID_CURVE;

        for (const actionType of ['expire', 'abandon']) {
            const result = replay(
                rv.server_seed,
                rv.client_seed,
                round(null, [{ actionIndex: 1, actionType, payload: new Uint8Array() }]),
                STAKE_MUTEZ,
            );

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe('lose');
            expect(result.cumulativePpm).toBe(0n);
            expect(result.payoutUnits).toBe(0n);
        }
    });

    it('settles an auto-round abandon exactly as the cashout at the target (sec-28)', () => {
        // The kernel substitutes `Cashout { tick: target }` for a system abandon
        // on an auto round — the action the sweep itself writes — so a forged
        // abandon on an auto winner pays the win.
        const rv = MID_CURVE;
        const target = Number(AUTO_TICK);
        const viaCashout = replay(rv.server_seed, rv.client_seed, round(target, [cashout(target)]), STAKE_MUTEZ);
        const viaAbandon = replay(
            rv.server_seed,
            rv.client_seed,
            round(target, [{ actionIndex: 1, actionType: 'abandon', payload: new Uint8Array() }]),
            STAKE_MUTEZ,
        );

        expect(viaAbandon.settled).toBe(true);
        expect(viaAbandon.outcome).toBe('cashout');
        expect(viaAbandon.cumulativePpm).toBe(viaCashout.cumulativePpm);
        // Consistency only; payout math is pinned by the transcript_vectors below.
        expect(viaAbandon.payoutUnits).toBe(payoutUnits(STAKE_MUTEZ, multiplierPpm(AUTO_TICK)));
        expect(viaAbandon.steps[1].title).toContain(`target tick ${target}`);

        // And an auto target past the crash is a determined loss either way.
        const lost = replay(
            rv.server_seed,
            rv.client_seed,
            round(Number(CRASH_TICK), [{ actionIndex: 1, actionType: 'abandon', payload: new Uint8Array() }]),
            STAKE_MUTEZ,
        );

        expect(lost.outcome).toBe('lose');
        expect(lost.payoutUnits).toBe(0n);
    });

    it('NEGATIVE: one mutated payload byte changes the payout, so the replay check fails', () => {
        const rv = MID_CURVE;
        const honestTick = Number(LAST_WIN_TICK);
        const honest = round(null, [cashout(honestTick)]);
        const honestResult = replay(rv.server_seed, rv.client_seed, honest, STAKE_MUTEZ);
        const claimedPayout = honestResult.payoutUnits;

        // Flip the low byte of the borsh u32 tick one tick earlier. The predicate
        // keeps the crash tick below 256, so the whole tick lives in byte 0.
        expect(honestTick).toBeLessThan(256);

        const tampered = round(null, [cashout(honestTick)]);

        tampered[1].payload[0] = honestTick - 1;

        const tamperedResult = replay(rv.server_seed, rv.client_seed, tampered, STAKE_MUTEZ);

        expect(tamperedResult.cumulativePpm).not.toBe(honestResult.cumulativePpm);
        expect(tamperedResult.cumulativePpm).toBe(multiplierPpm(LAST_WIN_TICK - 1n));

        // This is the comparison verifier.ts's `replay-payout` check makes: the
        // recomputed payout no longer equals the payout the transcript claimed.
        expect(tamperedResult.payoutUnits).not.toBe(claimedPayout);
    });

    it('rejects a malformed transcript', () => {
        const rv = MID_CURVE;
        const rejects = (actions: TranscriptAction[]) =>
            expect(() => replay(rv.server_seed, rv.client_seed, actions, STAKE_MUTEZ)).toThrow(ReplayError);

        rejects([]);
        rejects([cashout(1)]); // no place-bet at index 0
        rejects(round(null, [cashout(1), cashout(2)])); // a second in-round action
        rejects(round(null, [{ actionIndex: 1, actionType: 'reveal', payload: new Uint8Array() }]));
        rejects(round(null, [{ actionIndex: 1, actionType: 'cashout', payload: new Uint8Array([1, 2, 3]) }]));
        rejects([{ actionIndex: 0, actionType: 'place-bet', payload: new Uint8Array([0x02]) }]);
        rejects([{ actionIndex: 0, actionType: 'place-bet', payload: new Uint8Array([0x00, 0x00]) }]);
    });

    it('is registered with the verifier', () => {
        expect(supportedGameTypes()).toHaveLength(4);
        expect(supportedGameTypes()).toContain(GAME_TYPE);
    });
});

// ── whole rounds, against the Rust engine's own bytes ───────────────────

describe('crash:v1 transcript vectors', () => {
    // Everything above pins the CURVE: seeds, multipliers, crash ticks. These
    // rows pin the ROUND — the exact Borsh payload bytes the shipped Rust
    // adapter writes for each action, and the outcome and payout the shipped
    // Rust engine produces from them. Nothing here is hand-derived: the
    // payloads are decoded from the file rather than rebuilt by this test's own
    // encoder, which is the point. A Rust-side layout change (a field reordered,
    // a width narrowed, `Option` tagging altered) cannot pass this file by.

    const TRANSCRIPT_VECTORS = vectors.transcript_vectors;

    function actionsOf(vector: TranscriptVector): TranscriptAction[] {
        return vector.actions.map((action) => ({
            actionIndex: action.index,
            actionType: action.action_type,
            payload: hexToBytes(action.payload_hex),
        }));
    }

    it('has vectors covering every action type, or the walk below is vacuous', () => {
        expect(TRANSCRIPT_VECTORS.length).toBeGreaterThanOrEqual(7);

        const types = new Set(TRANSCRIPT_VECTORS.flatMap((v) => v.actions.map((a) => a.action_type)));

        // All three, because each exercises a different arm of the replayer:
        // the config decode, the claimed-tick comparison, and the system
        // settle that takes no payload at all.
        expect(types).toEqual(new Set(['place-bet', 'cashout', 'expire']));
        // Both outcomes, or a replayer that returned one constant would pass.
        expect(TRANSCRIPT_VECTORS.some((v) => v.expected_outcome === 'cashout')).toBe(true);
        expect(TRANSCRIPT_VECTORS.some((v) => v.expected_outcome === 'lose')).toBe(true);
    });

    it.each(TRANSCRIPT_VECTORS.map((vector) => [vector.name, vector] as const))(
        'replays %s to the Rust engine’s own outcome and payout',
        (_name, vector) => {
            const result = replay(vector.server_seed, vector.client_seed, actionsOf(vector), BigInt(vector.stake_units));

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe(vector.expected_outcome);
            expect(result.cumulativePpm).toBe(BigInt(vector.expected_cumulative_ppm));
            // The payout rule at the trust boundary, at the asset's 6 dp — the
            // figure `verifier.ts`'s `replay-payout` check compares with.
            expect(result.payoutUnits).toBe(BigInt(vector.expected_payout_units));
            expect(result.steps.map((step) => step.actionType)).toEqual(
                vector.actions.map((action) => action.action_type),
            );
        },
    );

    it('decodes each vector’s config and claimed tick from the file’s own bytes', () => {
        // The payload bytes are load-bearing and not decoration: read them back
        // through the decoders the replay itself uses, so a row whose hex the
        // replayer happened to ignore cannot sit here looking checked.
        for (const vector of TRANSCRIPT_VECTORS) {
            const actions = actionsOf(vector);
            const config = decodeConfig(actions[0].payload);
            const settle = actions[1];

            if (config.autoCashoutTick === null) {
                expect(actions[0].payload).toEqual(new Uint8Array([0x00]));
            } else {
                expect(actions[0].payload[0]).toBe(0x01);
                expect(actions[0].payload).toHaveLength(5);
            }

            if (settle.actionType === 'cashout') {
                const claimed = decodeCashoutTick(settle.payload);

                expect(settle.payload).toHaveLength(4);
                // An AUTO round's settling cashout is the sweep writing the
                // pre-committed target back, so the two numbers must agree.
                if (config.autoCashoutTick !== null) {
                    expect(claimed).toBe(config.autoCashoutTick);
                }
            } else {
                expect(settle.actionType).toBe('expire');
                expect(settle.payload).toHaveLength(0);
            }
        }
    });
});
