// @vitest-environment node
// Cross-runtime equivalence: this TS implementation must reproduce the SAME
// vectors.json the native Rust engine pins against (generated by the
// independent python3 reference libs/games/scripts/gen_vectors.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { vectorsUrl } from './vectors-path';
import { describe, expect, it } from 'vitest';
import { decimalStringToUnits, payoutUnits, unitsToDecimalString } from './ints';
import { bytesToHex, deriveSeed, rawU64 } from './seed';
import { GAME_TYPE, hiloStep, replay } from './hilo';
import type { TranscriptAction } from './types';

interface StepVector {
    server_seed: string;
    client_seed: string;
    action_index: number;
    seed_hex: string;
    raw_u64: string;
    deck_index: number;
    card: { rank: string; suit: string };
    rank_numeric: number;
    lower_probability_ppm: number;
    lower_multiplier_ppm: number;
    higher_probability_ppm: number;
    higher_multiplier_ppm: number;
}

interface RoundVector {
    server_seed: string;
    client_seed: string;
    stake: string;
    steps: {
        action_index: number;
        action: string;
        win?: boolean;
        step_multiplier_ppm?: number;
        cumulative_multiplier_ppm: number;
    }[];
    final: { outcome: string; cumulative_multiplier_ppm: number; payout: string };
}

const vectors: { step_vectors: StepVector[]; round_vectors: RoundVector[] } = JSON.parse(
    readFileSync(
        fileURLToPath(vectorsUrl('hilo')),
        'utf8',
    ),
);

const OUTCOME_BY_VECTOR: Record<string, string> = { 'cashed-out': 'cashout', lost: 'lose' };

describe('hilo:v1 vectors', () => {
    it('reproduces every step vector (seed, card, probabilities, multipliers)', () => {
        for (const sv of vectors.step_vectors) {
            const seed = deriveSeed(GAME_TYPE, sv.server_seed, sv.client_seed, sv.action_index);

            expect(bytesToHex(seed)).toBe(sv.seed_hex);
            expect(rawU64(seed).toString()).toBe(sv.raw_u64);

            const step = hiloStep(sv.server_seed, sv.client_seed, sv.action_index);

            expect(step.deckIndex).toBe(sv.deck_index);
            expect(step.rank).toBe(sv.card.rank);
            expect(step.suit).toBe(sv.card.suit);
            expect(step.rankNumeric).toBe(sv.rank_numeric);
            expect(step.lowerProbabilityPpm).toBe(BigInt(sv.lower_probability_ppm));
            expect(step.lowerMultiplierPpm).toBe(BigInt(sv.lower_multiplier_ppm));
            expect(step.higherProbabilityPpm).toBe(BigInt(sv.higher_probability_ppm));
            expect(step.higherMultiplierPpm).toBe(BigInt(sv.higher_multiplier_ppm));
        }
    });

    it('replays every round vector to the exact cumulative multiplier and payout', () => {
        for (const rv of vectors.round_vectors) {
            const actions: TranscriptAction[] = rv.steps.map((s) => ({
                actionIndex: s.action_index,
                actionType: s.action,
                payload: new Uint8Array(),
            }));
            const result = replay(rv.server_seed, rv.client_seed, actions);

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe(OUTCOME_BY_VECTOR[rv.final.outcome]);
            expect(result.cumulativePpm).toBe(BigInt(rv.final.cumulative_multiplier_ppm));

            for (const [i, s] of rv.steps.entries()) {
                expect(result.steps[i].cumulativePpm).toBe(BigInt(s.cumulative_multiplier_ppm));
            }

            // Payout in micro-units: stake × cum / 1e6 (exact for these stakes).
            const stakeUnits = decimalStringToUnits(rv.stake, 6);
            const payout = payoutUnits(stakeUnits, result.cumulativePpm);

            expect(unitsToDecimalString(payout, 6)).toBe(rv.final.payout);
        }
    });
});
