// @vitest-environment node
// Cross-runtime equivalence: this TS implementation must reproduce the SAME
// vectors.json the native Rust engine pins against (generated by the
// independent python3 reference libs/games/scripts/gen_vectors.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { vectorsUrl } from './vectors-path';
import { decimalStringToUnits, unitsToDecimalString } from './ints';
import { bytesToHex, hexToBytes, SeedStream } from './seed';
import { ARMOURS, GAME_TYPE, HEROES, SPRITES, WEAPONS, hydraRolls, replay } from './hydra';
import { ReplayError, type TranscriptAction } from './types';

interface RollVector {
    server_seed: string;
    client_seed: string;
    decision: number;
    seed_hex: string;
    raw_u64: string[];
    roll_ppm: number[];
}

interface Fight {
    stage: number;
    decision: number;
    fight_roll_ppm: number;
    damage_roll_ppm: number;
    death_probability_ppm: number;
    survived: boolean;
    wounded: boolean;
    damage_dealt: number;
    wound_threshold_ppm?: number;
    step_multiplier_ppm: number;
}

interface RoundStep {
    action_index: number;
    action: string;
    payload_borsh_hex: string;
    gear?: {
        weapon: string;
        armour: string;
        sprite: string;
    };
    fight?: Fight;
    effect: string;
    multiplier_ppm: number;
    cumulative_multiplier_ppm: number;
    banked: string;
    live_value: string;
    amount_won: string;
}

interface RoundVector {
    name: string;
    server_seed: string;
    client_seed: string;
    hero: number;
    weapon: number;
    armour: number;
    sprite: number;
    stake: string;
    steps: RoundStep[];
    final: { outcome: string; cumulative_multiplier_ppm: number; payout: string };
}

const vectors: { roll_vectors: RollVector[]; round_vectors: RoundVector[] } = JSON.parse(
    readFileSync(fileURLToPath(vectorsUrl('hydra')), 'utf8'),
);

function actionsOf(rv: RoundVector): TranscriptAction[] {
    return rv.steps.map((s) => ({
        actionIndex: s.action_index,
        actionType: s.action,
        payload: hexToBytes(s.payload_borsh_hex),
    }));
}

function named(name: string): RoundVector {
    const rv = vectors.round_vectors.find((candidate) => candidate.name === name);

    if (rv === undefined) {
        throw new Error(`hydra vectors.json has no round named ${name}`);
    }

    return rv;
}

function replayVector(rv: RoundVector, actions: TranscriptAction[] = actionsOf(rv)) {
    return replay(rv.server_seed, rv.client_seed, actions, decimalStringToUnits(rv.stake, 6));
}

const action = (actionIndex: number, actionType: string, payload: Uint8Array = new Uint8Array()): TranscriptAction => ({
    actionIndex,
    actionType,
    payload,
});

/** `borsh(partial_cashout::Payload { amount: u128 })`. */
function bank(actionIndex: number, units: bigint): TranscriptAction {
    return action(
        actionIndex,
        'partial-cashout',
        Uint8Array.from({ length: 16 }, (_, i) => Number((units >> BigInt(8 * i)) & 0xffn)),
    );
}

describe('hydra:v1 vectors', () => {
    it('reproduces every roll vector, raw u64 and Lemire ppm', () => {
        expect(vectors.roll_vectors.length).toBeGreaterThan(0);

        for (const v of vectors.roll_vectors) {
            const rolls = hydraRolls(v.server_seed, v.client_seed, v.decision, v.raw_u64.length);
            const stream = new SeedStream(GAME_TYPE, v.server_seed, v.client_seed, v.decision);

            stream.take(1);
            expect(bytesToHex(stream.derivedChunks()[0])).toBe(v.seed_hex);
            expect(rolls.map((r) => r.raw.toString())).toEqual(v.raw_u64);
            expect(rolls.map((r) => Number(r.ppm))).toEqual(v.roll_ppm);
        }
    });

    it('covers potion, mana, magic, partial-cashout, abandon, death and a full clear', () => {
        // The scenarios this port depends on. If a regeneration drops one,
        // the per-round assertions below would silently stop covering it.
        const actionsSeen = new Set(vectors.round_vectors.flatMap((rv) => rv.steps.map((s) => s.action)));

        for (const needed of [
            'physical-attack',
            'magic-attack',
            'drink-potion',
            'drink-mana',
            'partial-cashout',
            'cashout',
            'abandon',
        ]) {
            expect(actionsSeen).toContain(needed);
        }

        const outcomes = new Set(vectors.round_vectors.map((rv) => rv.final.outcome));

        expect(outcomes).toEqual(new Set(['abandoned', 'bust', 'cashed-out', 'completed']));
        expect(vectors.round_vectors.some((rv) => rv.steps.some((s) => s.fight?.wounded))).toBe(true);
        expect(vectors.round_vectors.some((rv) => rv.steps.some((s) => s.fight?.damage_dealt === 0))).toBe(true);
        expect(vectors.round_vectors.some((rv) => rv.steps.some((s) => s.fight?.damage_dealt === 2))).toBe(true);
    });

    for (const rv of vectors.round_vectors) {
        it(`replays round "${rv.name}" step by step`, () => {
            const result = replayVector(rv);

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe(rv.final.outcome);
            expect(result.cumulativePpm).toBe(BigInt(rv.final.cumulative_multiplier_ppm));
            expect(unitsToDecimalString(result.payoutUnits, 6)).toBe(rv.final.payout);
            expect(result.settledAtIndex).toBe(rv.steps[rv.steps.length - 1].action_index);
            expect(result.steps).toHaveLength(rv.steps.length);
            expect(unitsToDecimalString(result.bankedUnits, 6)).toBe(rv.steps[rv.steps.length - 1].banked);

            for (const [i, s] of rv.steps.entries()) {
                const replayed = result.steps[i];

                expect(replayed.actionIndex).toBe(s.action_index);
                expect(replayed.cumulativePpm).toBe(BigInt(s.cumulative_multiplier_ppm));

                if (s.gear !== undefined) {
                    expect([WEAPONS[rv.weapon].name, ARMOURS[rv.armour].name, SPRITES[rv.sprite].name]).toEqual([
                        s.gear.weapon,
                        s.gear.armour,
                        s.gear.sprite,
                    ]);
                    expect(replayed.title).toContain(
                        `${HEROES[rv.hero].name} with ${s.gear.weapon} weapon, ${s.gear.armour} armour, ${s.gear.sprite} sprite`,
                    );
                    expect(WEAPONS.map((w) => w.name)).toContain(s.gear.weapon);
                    expect(ARMOURS.map((a) => a.name)).toContain(s.gear.armour);
                    expect(SPRITES.map((p) => p.name)).toContain(s.gear.sprite);
                }

                if (s.fight !== undefined) {
                    const detail = Object.fromEntries(replayed.details);

                    expect(detail.decision).toBe(String(s.fight.decision));
                    expect(detail['fight roll (bytes [0..8))']).toMatch(new RegExp(`→ ${s.fight.fight_roll_ppm} ppm$`));
                    expect(detail['damage roll (bytes [8..16))']).toMatch(
                        new RegExp(`→ ${s.fight.damage_roll_ppm} ppm$`),
                    );
                    expect(detail['death probability']).toMatch(new RegExp(`^${s.fight.death_probability_ppm} ppm`));

                    if (s.fight.survived) {
                        expect(detail['wound threshold']).toMatch(new RegExp(`^${s.fight.wound_threshold_ppm} ppm`));
                        expect(detail['wound threshold'].includes('wounded')).toBe(s.fight.wounded);
                        expect(detail.damage).toMatch(new RegExp(`^${s.fight.damage_dealt} `));
                    } else {
                        expect(replayed.title).toContain('DIED');
                    }
                }
            }
        });
    }
});

describe('hydra:v1 transcript rules', () => {
    const bankRound = named('bank-then-cashout-pays-banked-plus-live');
    const clearRound = named('wins-all-12-stages');

    it('a system partial-cashout does not move any later roll', () => {
        // Strip the bank: every attack keeps its decision, so the fight and
        // damage rolls and the cumulative chain are identical; only the
        // banked/live split differs.
        const withBank = replayVector(bankRound);
        const withoutBank = replayVector(
            bankRound,
            actionsOf(bankRound)
                .filter((a) => a.actionType !== 'partial-cashout')
                .map((a, actionIndex) => ({ ...a, actionIndex })),
        );
        const fightDetails = (r: typeof withBank) =>
            r.steps.filter((s) => s.actionType === 'physical-attack').map((s) => s.details.slice(0, 5));

        expect(fightDetails(withoutBank)).toEqual(fightDetails(withBank));
        expect(withoutBank.cumulativePpm).toBe(withBank.cumulativePpm);
        expect(withBank.bankedUnits).toBe(50_000_000n);
        expect(withoutBank.bankedUnits).toBe(0n);
    });

    it('free potions and mana do not move any later roll either', () => {
        // The full clear interleaves potions/mana between attacks; its fight
        // decisions are exactly 0..n-1, one per attack (the bet draws nothing).
        const result = replayVector(clearRound);
        const decisions = result.steps
            .filter((s) => s.actionType.endsWith('-attack'))
            .map((s) => Object.fromEntries(s.details).decision);

        expect(decisions).toEqual(decisions.map((_, i) => String(i)));
    });

    it('abandon before the first attack pays the stake, ending abandoned', () => {
        const rv = named('abandon-before-first-attack-pays-stake');
        const result = replayVector(rv);

        expect(result.outcome).toBe('abandoned');
        expect(result.payoutUnits).toBe(100_000_000n);
    });

    it('death after a bank pays the banked total', () => {
        const result = replayVector(named('bank-then-death-pays-banked'));

        expect(result.outcome).toBe('bust');
        expect(result.cumulativePpm).toBe(0n);
        expect(result.payoutUnits).toBe(result.bankedUnits);
        expect(result.payoutUnits).toBe(50_000_000n);
    });

    it('stops at the settling action and never reads what follows', () => {
        const rv = named('dies-on-attack-3');
        const actions = actionsOf(rv);
        const padded = [...actions, action(actions.length, 'cashout'), action(actions.length + 1, 'bogus')];
        const result = replayVector(rv, padded);

        expect(result.settledAtIndex).toBe(actions.length - 1);
        expect(result.steps).toHaveLength(actions.length);
        expect(unitsToDecimalString(result.payoutUnits, 6)).toBe(rv.final.payout);
    });

    it('is unsettled when the transcript stops mid-round', () => {
        const actions = actionsOf(bankRound).slice(0, 2);
        const result = replayVector(bankRound, actions);

        expect(result.settled).toBe(false);
        expect(result.settledAtIndex).toBeNull();
    });

    describe('rejects what the engine rejects', () => {
        /** Knight on common/cloth/common: `borsh(Config)`, four bytes. */
        const knight = new Uint8Array([1, 0, 0, 0]);
        const seeds = [bankRound.server_seed, bankRound.client_seed] as const;
        const run = (actions: TranscriptAction[]) => () => replay(...seeds, actions, 100_000_000n);
        const firstAttack = actionsOf(bankRound).slice(0, 2);

        it.each([
            ['an empty transcript', []],
            ['a transcript not opening with place-bet', [action(0, 'physical-attack')]],
            ['an empty config payload', [action(0, 'place-bet')]],
            ['a hero-only payload (the pre-gear layout)', [action(0, 'place-bet', new Uint8Array([1]))]],
            ['a five-byte config payload', [action(0, 'place-bet', new Uint8Array([1, 0, 0, 0, 0]))]],
            ['an unknown hero', [action(0, 'place-bet', new Uint8Array([6, 0, 0, 0]))]],
            ['an unknown weapon tier', [action(0, 'place-bet', new Uint8Array([1, 3, 0, 0]))]],
            ['an unknown armour tier', [action(0, 'place-bet', new Uint8Array([1, 0, 3, 0]))]],
            ['an unknown sprite tier', [action(0, 'place-bet', new Uint8Array([1, 0, 0, 3]))]],
            ['a second place-bet', [action(0, 'place-bet', knight), action(1, 'place-bet', knight)]],
            ['a cashout before the first attack', [action(0, 'place-bet', knight), action(1, 'cashout')]],
            ['a potion before the first attack', [action(0, 'place-bet', knight), action(1, 'drink-potion')]],
            ['mana before the first attack', [action(0, 'place-bet', knight), action(1, 'drink-mana')]],
            ['an unknown action', [action(0, 'place-bet', knight), action(1, 'higher')]],
            ['a payload on a payload-free action', [action(0, 'place-bet', knight), action(1, 'physical-attack', new Uint8Array([0]))]],
            ['a bank larger than the live position', [...firstAttack, bank(2, 10_000_000_000n)]],
            ['a zero bank', [...firstAttack, bank(2, 0n)]],
        ] as [string, TranscriptAction[]][])('%s', (_, actions) => {
            expect(run(actions)).toThrow(ReplayError);
        });

        it('accepts the fixture bet itself, so each refusal above is its own', () => {
            expect(run([action(0, 'place-bet', knight)])).not.toThrow();
        });

        it('a magic attack with no mana left', () => {
            // Hercules has 1 MP: the first magic attack spends it. Find a seed
            // pair where it survives, so the second one meets an empty pool.
            const hercules = new Uint8Array([0, 0, 0, 0]);
            const magic = [action(0, 'place-bet', hercules), action(1, 'magic-attack')];
            const survivor = Array.from({ length: 200 }, (_, n) => `server-${n}`).find(
                (server) => !replay(server, 'client-seed', magic, 100_000_000n).settled,
            );

            expect(survivor).toBeDefined();
            expect(() =>
                replay(survivor as string, 'client-seed', [...magic, action(2, 'magic-attack')], 100_000_000n),
            ).toThrow(/no mana/);
        });

        it('a potion at full HP and mana at full MP', () => {
            // After the wounded first attack of this round HP is 3/4 and MP
            // is untouched at 1/1: one potion is legal, a second is not, and
            // mana is never legal.
            const rv = named('wounded-then-potion-then-cashout');
            const opening = actionsOf(rv).slice(0, 3);

            expect(opening.map((a) => a.actionType)).toEqual(['place-bet', 'physical-attack', 'drink-potion']);
            expect(() => replayVector(rv, [...opening, action(3, 'drink-potion')])).toThrow(/full HP/);
            expect(() => replayVector(rv, [...opening.slice(0, 2), action(2, 'drink-mana')])).toThrow(/full MP/);
        });
    });
});
