// @vitest-environment node
// Cross-runtime equivalence: this TS implementation must reproduce the SAME
// vectors.json the native Rust engine pins against (generated by the
// independent python3 reference libs/games/scripts/gen_vectors.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { vectorsUrl } from './vectors-path';
import { describe, expect, it } from 'vitest';
import { decimalStringToUnits, divHalfUp, unitsToDecimalString } from './ints';
import { hexToBytes } from './seed';
import { deriveLayout, replay, stepMultiplierPpm, TOTAL_TILES } from './mines';
import { mulPpm, SCALE_PPM } from './ints';
import type { TranscriptAction } from './types';

interface LayoutVector {
    server_seed: string;
    client_seed: string;
    mine_count: number;
    mine_positions: number[];
    layout_draws: { draw: number; raw_u32: number; swap_index: number }[];
}

interface RoundVector {
    server_seed: string;
    client_seed: string;
    mine_count: number;
    stake: string;
    mine_positions: number[];
    steps: {
        action_index: number;
        action: string;
        payload_borsh_hex?: string;
        place_bet_payload_borsh_hex?: string;
        is_mine?: boolean;
        step_multiplier_ppm?: number;
        banked_micro?: number;
        cumulative_multiplier_ppm: number;
    }[];
    final: { outcome: string; cumulative_multiplier_ppm: number; payout: string };
}

const vectors: {
    layout_vectors: LayoutVector[];
    multiplier_tables: { mine_count: number; cumulative_multiplier_ppm: number[] }[];
    round_vectors: RoundVector[];
} = JSON.parse(
    readFileSync(
        fileURLToPath(vectorsUrl('mines')),
        'utf8',
    ),
);

const OUTCOME_BY_VECTOR: Record<string, string> = { 'cashed-out': 'cashout', lost: 'lose', won: 'win' };

describe('mines:v1 vectors', () => {
    it('reproduces every layout vector including the draw intermediates', () => {
        for (const lv of vectors.layout_vectors) {
            const layout = deriveLayout(lv.server_seed, lv.client_seed, lv.mine_count);

            expect(layout.minePositions).toEqual(lv.mine_positions);
            expect(layout.draws.map((d) => ({ draw: d.draw, raw_u32: d.rawU32, swap_index: d.swapIndex }))).toEqual(
                lv.layout_draws,
            );
        }
    });

    it('reproduces every cumulative multiplier table (all 24 mine counts)', () => {
        expect(vectors.multiplier_tables).toHaveLength(24);

        for (const mt of vectors.multiplier_tables) {
            expect(mt.cumulative_multiplier_ppm).toHaveLength(TOTAL_TILES - mt.mine_count);

            let cumulative = SCALE_PPM;

            for (const [k, expected] of mt.cumulative_multiplier_ppm.entries()) {
                cumulative = mulPpm(cumulative, stepMultiplierPpm(mt.mine_count, k));

                expect(cumulative).toBe(BigInt(expected));
            }
        }
    });

    it('replays every round vector to the exact cumulative multiplier and payout', () => {
        for (const rv of vectors.round_vectors) {
            const actions: TranscriptAction[] = rv.steps.map((s) => ({
                actionIndex: s.action_index,
                actionType: s.action,
                payload: hexToBytes(s.payload_borsh_hex ?? s.place_bet_payload_borsh_hex ?? ''),
            }));
            const result = replay(rv.server_seed, rv.client_seed, actions);

            expect(result.settled).toBe(true);
            expect(result.outcome).toBe(OUTCOME_BY_VECTOR[rv.final.outcome]);
            expect(result.cumulativePpm).toBe(BigInt(rv.final.cumulative_multiplier_ppm));

            for (const [i, s] of rv.steps.entries()) {
                expect(result.steps[i].cumulativePpm).toBe(BigInt(s.cumulative_multiplier_ppm));
            }

            // Payout via the banked/live fold, in integer micro-units: each
            // safe reveal folds live' = half_up(live × step / 1e6); a bank
            // moves value from live to banked; a mine hit zeroes live. The
            // final payout is banked + live (the vectors' documented value
            // model).
            let liveUnits = decimalStringToUnits(rv.stake, 6);
            let bankedUnits = 0n;

            for (const s of rv.steps) {
                if (s.action === 'partial-cashout') {
                    const amount = BigInt(s.banked_micro ?? 0);

                    bankedUnits += amount;
                    liveUnits -= amount;
                } else if (s.is_mine === false) {
                    liveUnits = divHalfUp(liveUnits * BigInt(s.step_multiplier_ppm ?? 0), 1_000_000n);
                } else if (s.is_mine === true) {
                    liveUnits = 0n;
                }
            }

            expect(unitsToDecimalString(bankedUnits + liveUnits, 6)).toBe(rv.final.payout);
        }
    });
});
