// @vitest-environment node
// Cross-runtime equivalence: this TS implementation must reproduce the SAME
// vectors.json the native Rust engine pins against (generated by the
// independent python3 reference libs/games/scripts/gen_vectors.py).
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { vectorsUrl } from './vectors-path';
import { describe, expect, it } from 'vitest';
import { decimalStringToUnits, payoutUnits, unitsToDecimalString } from './ints';
import { bytesToHex, deriveSeed, hexToBytes } from './seed';
import { GAME_TYPE, binIndex, derivePath, exactRtp, multipliers, replay, type Risk } from './plinko';

interface TableVector {
    rows: number;
    risk: Risk;
    multipliers_ppm: number[];
    rtp_weighted_sum: string;
    rtp_denominator: string;
    rtp_ppm_exact: string;
}

interface RoundVector {
    server_seed: string;
    client_seed: string;
    rows: number;
    risk: Risk;
    place_bet_payload_borsh_hex: string;
    stake: string;
    seed_hex: string;
    path: number[];
    bin_index: number;
    multiplier_ppm: number;
    payout: string;
}

const vectors: { tables: TableVector[]; round_vectors: RoundVector[] } = JSON.parse(
    readFileSync(
        fileURLToPath(vectorsUrl('plinko')),
        'utf8',
    ),
);

describe('plinko:v1 vectors', () => {
    it('reproduces every multiplier table and its exact RTP fraction', () => {
        expect(vectors.tables).toHaveLength(15);

        for (const tv of vectors.tables) {
            expect(multipliers(tv.rows, tv.risk).map(Number)).toEqual(tv.multipliers_ppm);

            const rtp = exactRtp(tv.rows, tv.risk);

            expect(rtp.weightedSum.toString()).toBe(tv.rtp_weighted_sum);
            expect(rtp.denominator.toString()).toBe(tv.rtp_denominator);
            expect(rtp.display).toBe(`${tv.rtp_ppm_exact} ppm`);

            // The repo's namesake guarantee, re-checked in exact arithmetic:
            // 995_000 ≤ RTP ≤ 995_500 ppm for every table.
            expect(rtp.weightedSum >= 995_000n * rtp.denominator).toBe(true);
            expect(rtp.weightedSum <= 995_500n * rtp.denominator).toBe(true);
        }
    });

    it('replays every round vector to the exact path, bin, multiplier, payout', () => {
        for (const rv of vectors.round_vectors) {
            const seed = deriveSeed(GAME_TYPE, rv.server_seed, rv.client_seed, 0);

            expect(bytesToHex(seed)).toBe(rv.seed_hex);
            expect(derivePath(seed, rv.rows)).toEqual(rv.path);
            expect(binIndex(rv.path)).toBe(rv.bin_index);

            const result = replay(rv.server_seed, rv.client_seed, [
                {
                    actionIndex: 0,
                    actionType: 'place-bet',
                    payload: hexToBytes(rv.place_bet_payload_borsh_hex),
                },
                { actionIndex: 1, actionType: 'cashout', payload: new Uint8Array() },
            ]);

            expect(result.settled).toBe(true);
            expect(result.cumulativePpm).toBe(BigInt(rv.multiplier_ppm));

            const stakeUnits = decimalStringToUnits(rv.stake, 6);

            expect(unitsToDecimalString(payoutUnits(stakeUnits, result.cumulativePpm), 6)).toBe(rv.payout);
        }
    });
});
